using System;

namespace Test_Console
{
    public class VO_RawFaraggi
    {
        public object IdLiquidacion { set; get; }
        public object Poliza { set; get; }
        public object Digito { set; get; }
        public object TipoPoliza { set; get; }
        public DateTime? Inic_Pol { set; get; }
        public DateTime? Fin_Pol { set; get; }
        public object Grupo { set; get; }
        public object SubPoliza { set; get; }
        public object IdAsegurados { set; get; }
        public object IdBeneficiario { set; get; }
        public object Rut { set; get; }
        public object dv { set; get; }
        public object nsecuencia { set; get; }
        public object Titular { set; get; }
        public object Beneficiario { set; get; }
        public object BeneficiarioRut { set; get; }
        public object BeneficiarioDv { set; get; }
        public DateTime? Fecha_nacimiento_Titular { set; get; }
        public DateTime? Fecha_nacimiento_Beneficiario { set; get; }
        public DateTime? Inic_Aseg { set; get; }
        public DateTime? Fin_Aseg { set; get; }
        public object Sucursal { set; get; }
        public object BeneficiarioRelParentesco { set; get; }
        public object Folio { set; get; }
        public DateTime? FechaPago { set; get; }
        public object DiagnosticoCodigo { set; get; }
        public object DiagnosticoNombre { set; get; }
        public object PrestadorRut { set; get; }
        public object Prestadordv { set; get; }
        public object PrestadorRazonSocial { set; get; }
        public object PrestacionesCodigo { set; get; }
        public object PrestacionesNombre { set; get; }
        public object Codigo_Fonasa { set; get; }
        public object Descripcion_Fonasa { set; get; }
        public object TipoPrestacion { set; get; }
        public DateTime? FechaPrestacion { set; get; }
        public object Isapre { set; get; }
        public object ValorUF { set; get; }
        public object idliquidacion_det { set; get; }
        public object Cantidad { set; get; }
        public object ValorPrestacion { set; get; }
        public object BonIsapre { set; get; }
        public object CoPago { set; get; }
        public object Deducible { set; get; }
        public object ValorPago { set; get; }
        public object ValorPrestacionUF { set; get; }
        public object BonIsapreUF { set; get; }
        public object CoPagoUF { set; get; }
        public object DeducibleUF { set; get; }
        public object ValorPagoUF { set; get; }
        public object TM { set; get; }
        public object TMP { set; get; }
        public object DM { set; get; }
        public object PorcReembolso { set; get; }
        public object BeneficioMinimo { set; get; }
        public DateTime? FechaIngreso { set; get; }
        public DateTime? FechaLiquidacion { set; get; }
        public object TieneBeneficioMinimo { set; get; }
        public object PorcentajeBeneficioMinimo { set; get; }
        public object Estado { set; get; }
        public object MovApertura { set; get; }
        public object Observaciones { set; get; }
        public object ObservacionInterna { set; get; }
        public object TipoDocumento { set; get; }
        public DateTime? FHCreacion { set; get; }
        public DateTime? FHModificacion { set; get; }
        public DateTime? FHTransaccion { set; get; }
        public object Liquidador { set; get; }
        public object CausalRechazo { set; get; }
        public object Imed { set; get; }
        public object Salco { set; get; }
        public object nsolicitud { set; get; }
        public object compania { set; get; }
        public object tipopago { set; get; }
        public object Contratante { set; get; }
        public object Corredor { set; get; }
        public object Estado_liquidacion_Encabezado { set; get; }
        public object Estado_liquidacion_Detalle { set; get; }
        public object Estado_Asegurado { set; get; }
        public object PlanAsegurados { set; get; }
        public object Tipo_de_Pago { set; get; }
        public object Banco { set; get; }
        public object NroCuenta { set; get; }
        public object Texto_Detalle { set; get; }
        public object IdTipoOperacion { set; get; }
        public object Tipo_Operacion { set; get; }
        public object Nro_Documento { set; get; }
        public object Id_ventanilla_Unica { set; get; }
        public object Nombre_ventanilla_Unica { set; get; }
        public object Deducible_individual_anual { set; get; }
        public object Deducible_Tope_familiar { set; get; }
        public object IdTipoPago { set; get; }
        public object Forma_de_Pago { set; get; }
        public object swCorreo_envio_Correo { set; get; }
        public object Liquidador_Crea { set; get; }
        public object Liquidador_Modifica { set; get; }
        public object Compania { set; get; }
        public object Holding { set; get; }
    }
}